version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: containernode
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/mysql
    container_name: container-mysql-kabum
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_DATABASE: "containermysqlkabum"
